lecteurcarte.o: lecteurcarte.c /shared/TCii/include/lcarte.h baseclient.h \
 lecteurcarte.h /shared/TCii/include/memoire_borne.h \
 /shared/TCii/include/donnees_borne.h
borne.o: borne.c /shared/TCii/include/memoire_borne.h \
 /shared/TCii/include/donnees_borne.h lecteurcarte.h
baseclient.o: baseclient.c baseclient.h
